services:
  postgres:
    image: ankane/pgvector:latest
    container_name: promptforge-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: promptforge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
